2025-04-13T16:12:06.2787500Z Requested labels: ubuntu-latest
2025-04-13T16:12:06.2787895Z Job defined at: microsoft/markitdown/.github/workflows/tests.yml@refs/pull/1176/merge
2025-04-13T16:12:06.2788028Z Waiting for a runner to pick up this job...
2025-04-13T16:12:07.5095708Z Job is waiting for a hosted runner to come online.
2025-04-13T16:12:10.5947740Z Job is about to start running on the hosted runner: GitHub Actions 920 (hosted)
2025-04-13T16:12:12.6943788Z Current runner version: '2.323.0'
2025-04-13T16:12:12.6968646Z ##[group]Operating System
2025-04-13T16:12:12.6969435Z Ubuntu
2025-04-13T16:12:12.6969892Z 24.04.2
2025-04-13T16:12:12.6970509Z LTS
2025-04-13T16:12:12.6971191Z ##[endgroup]
2025-04-13T16:12:12.6971792Z ##[group]Runner Image
2025-04-13T16:12:12.6972399Z Image: ubuntu-24.04
2025-04-13T16:12:12.6972900Z Version: 20250406.1.0
2025-04-13T16:12:12.6973982Z Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20250406.1/images/ubuntu/Ubuntu2404-Readme.md
2025-04-13T16:12:12.6975420Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250406.1
2025-04-13T16:12:12.6976346Z ##[endgroup]
2025-04-13T16:12:12.6976938Z ##[group]Runner Image Provisioner
2025-04-13T16:12:12.6977549Z 2.0.422.1
2025-04-13T16:12:12.6978025Z ##[endgroup]
2025-04-13T16:12:12.6979187Z ##[group]GITHUB_TOKEN Permissions
2025-04-13T16:12:12.6981330Z Contents: read
2025-04-13T16:12:12.6981988Z Metadata: read
2025-04-13T16:12:12.6982699Z Packages: read
2025-04-13T16:12:12.6983386Z ##[endgroup]
2025-04-13T16:12:12.6986432Z Secret source: None
2025-04-13T16:12:12.6987422Z Prepare workflow directory
2025-04-13T16:12:12.7292131Z Prepare all required actions
2025-04-13T16:12:12.7327931Z Getting action download info
2025-04-13T16:12:12.9368277Z ##[group]Download immutable action package 'actions/checkout@v4'
2025-04-13T16:12:12.9369215Z Version: 4.2.2
2025-04-13T16:12:12.9370115Z Digest: sha256:ccb2698953eaebd21c7bf6268a94f9c26518a7e38e27e0b83c1fe1ad049819b1
2025-04-13T16:12:12.9371440Z Source commit SHA: 11bd71901bbe5b1630ceea73d27597364c9af683
2025-04-13T16:12:12.9372148Z ##[endgroup]
2025-04-13T16:12:13.0245613Z ##[group]Download immutable action package 'actions/setup-python@v5'
2025-04-13T16:12:13.0246398Z Version: 5.5.0
2025-04-13T16:12:13.0247103Z Digest: sha256:1fac95d751afd58314aebd2ab01d4bf3b3109a441917bd2cac2a22898ec494f7
2025-04-13T16:12:13.0248037Z Source commit SHA: 8d9ed9ac5c53483de85588cdf95a591a75ab9f55
2025-04-13T16:12:13.0248705Z ##[endgroup]
2025-04-13T16:12:13.4518461Z Complete job name: tests
2025-04-13T16:12:13.5261005Z ##[group]Run actions/checkout@v4
2025-04-13T16:12:13.5261955Z with:
2025-04-13T16:12:13.5262464Z   repository: microsoft/markitdown
2025-04-13T16:12:13.5263217Z   token: ***
2025-04-13T16:12:13.5263649Z   ssh-strict: true
2025-04-13T16:12:13.5264092Z   ssh-user: git
2025-04-13T16:12:13.5264548Z   persist-credentials: true
2025-04-13T16:12:13.5265055Z   clean: true
2025-04-13T16:12:13.5265533Z   sparse-checkout-cone-mode: true
2025-04-13T16:12:13.5266074Z   fetch-depth: 1
2025-04-13T16:12:13.5266508Z   fetch-tags: false
2025-04-13T16:12:13.5266967Z   show-progress: true
2025-04-13T16:12:13.5267428Z   lfs: false
2025-04-13T16:12:13.5267854Z   submodules: false
2025-04-13T16:12:13.5268311Z   set-safe-directory: true
2025-04-13T16:12:13.5269042Z ##[endgroup]
2025-04-13T16:12:13.7039419Z Syncing repository: microsoft/markitdown
2025-04-13T16:12:13.7041554Z ##[group]Getting Git version info
2025-04-13T16:12:13.7042339Z Working directory is '/home/runner/work/markitdown/markitdown'
2025-04-13T16:12:13.7043708Z [command]/usr/bin/git version
2025-04-13T16:12:13.7091838Z git version 2.49.0
2025-04-13T16:12:13.7118668Z ##[endgroup]
2025-04-13T16:12:13.7132726Z Temporarily overriding HOME='/home/runner/work/_temp/2f4019c8-cebf-4cc2-8026-e42d9225f8ab' before making global git config changes
2025-04-13T16:12:13.7134190Z Adding repository directory to the temporary git global config as a safe directory
2025-04-13T16:12:13.7138357Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/markitdown/markitdown
2025-04-13T16:12:13.7179088Z Deleting the contents of '/home/runner/work/markitdown/markitdown'
2025-04-13T16:12:13.7183795Z ##[group]Initializing the repository
2025-04-13T16:12:13.7189311Z [command]/usr/bin/git init /home/runner/work/markitdown/markitdown
2025-04-13T16:12:13.7275123Z hint: Using 'master' as the name for the initial branch. This default branch name
2025-04-13T16:12:13.7276628Z hint: is subject to change. To configure the initial branch name to use in all
2025-04-13T16:12:13.7277961Z hint: of your new repositories, which will suppress this warning, call:
2025-04-13T16:12:13.7278707Z hint:
2025-04-13T16:12:13.7279254Z hint: 	git config --global init.defaultBranch <name>
2025-04-13T16:12:13.7280133Z hint:
2025-04-13T16:12:13.7281550Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2025-04-13T16:12:13.7283362Z hint: 'development'. The just-created branch can be renamed via this command:
2025-04-13T16:12:13.7284954Z hint:
2025-04-13T16:12:13.7285809Z hint: 	git branch -m <name>
2025-04-13T16:12:13.7287392Z Initialized empty Git repository in /home/runner/work/markitdown/markitdown/.git/
2025-04-13T16:12:13.7296067Z [command]/usr/bin/git remote add origin https://github.com/microsoft/markitdown
2025-04-13T16:12:13.7347956Z ##[endgroup]
2025-04-13T16:12:13.7348768Z ##[group]Disabling automatic garbage collection
2025-04-13T16:12:13.7354222Z [command]/usr/bin/git config --local gc.auto 0
2025-04-13T16:12:13.7388247Z ##[endgroup]
2025-04-13T16:12:13.7389038Z ##[group]Setting up auth
2025-04-13T16:12:13.7398392Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2025-04-13T16:12:13.7433436Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2025-04-13T16:12:13.7743302Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2025-04-13T16:12:13.7777051Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2025-04-13T16:12:13.8009322Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2025-04-13T16:12:13.8055505Z ##[endgroup]
2025-04-13T16:12:13.8056850Z ##[group]Fetching the repository
2025-04-13T16:12:13.8064747Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +521d33b41a2163b2857085a9cd21f84edbd5eb4b:refs/remotes/pull/1176/merge
2025-04-13T16:12:14.4531599Z From https://github.com/microsoft/markitdown
2025-04-13T16:12:14.4534777Z  * [new ref]         521d33b41a2163b2857085a9cd21f84edbd5eb4b -> pull/1176/merge
2025-04-13T16:12:14.4556541Z ##[endgroup]
2025-04-13T16:12:14.4558493Z ##[group]Determining the checkout info
2025-04-13T16:12:14.4560597Z ##[endgroup]
2025-04-13T16:12:14.4564863Z [command]/usr/bin/git sparse-checkout disable
2025-04-13T16:12:14.4608098Z [command]/usr/bin/git config --local --unset-all extensions.worktreeConfig
2025-04-13T16:12:14.4637278Z ##[group]Checking out the ref
2025-04-13T16:12:14.4640977Z [command]/usr/bin/git checkout --progress --force refs/remotes/pull/1176/merge
2025-04-13T16:12:14.4884721Z Note: switching to 'refs/remotes/pull/1176/merge'.
2025-04-13T16:12:14.4886010Z 
2025-04-13T16:12:14.4887069Z You are in 'detached HEAD' state. You can look around, make experimental
2025-04-13T16:12:14.4889480Z changes and commit them, and you can discard any commits you make in this
2025-04-13T16:12:14.4891694Z state without impacting any branches by switching back to a branch.
2025-04-13T16:12:14.4892694Z 
2025-04-13T16:12:14.4893670Z If you want to create a new branch to retain commits you create, you may
2025-04-13T16:12:14.4895242Z do so (now or later) by using -c with the switch command. Example:
2025-04-13T16:12:14.4896088Z 
2025-04-13T16:12:14.4896462Z   git switch -c <new-branch-name>
2025-04-13T16:12:14.4897064Z 
2025-04-13T16:12:14.4897408Z Or undo this operation with:
2025-04-13T16:12:14.4897956Z 
2025-04-13T16:12:14.4898262Z   git switch -
2025-04-13T16:12:14.4898697Z 
2025-04-13T16:12:14.4899425Z Turn off this advice by setting config variable advice.detachedHead to false
2025-04-13T16:12:14.4900638Z 
2025-04-13T16:12:14.4902283Z HEAD is now at 521d33b Merge 81f8a69a753568b71eab022731c9658e54775ffe into 3fcd48cdfc651cbf508071c8d2fb7d82aeb075de
2025-04-13T16:12:14.4907070Z ##[endgroup]
2025-04-13T16:12:14.4932347Z [command]/usr/bin/git log -1 --format=%H
2025-04-13T16:12:14.4955132Z 521d33b41a2163b2857085a9cd21f84edbd5eb4b
2025-04-13T16:12:14.5351685Z ##[group]Run actions/setup-python@v5
2025-04-13T16:12:14.5352956Z with:
2025-04-13T16:12:14.5353849Z   python-version: 3.10
3.11
3.12

2025-04-13T16:12:14.5355037Z   check-latest: false
2025-04-13T16:12:14.5356305Z   token: ***
2025-04-13T16:12:14.5357236Z   update-environment: true
2025-04-13T16:12:14.5358352Z   allow-prereleases: false
2025-04-13T16:12:14.5359465Z   freethreaded: false
2025-04-13T16:12:14.5360450Z ##[endgroup]
2025-04-13T16:12:14.7017890Z ##[group]Installed versions
2025-04-13T16:12:14.7086216Z Successfully set up CPython (3.10.16)
2025-04-13T16:12:14.7107837Z Successfully set up CPython (3.11.11)
2025-04-13T16:12:14.7125988Z Successfully set up CPython (3.12.9)
2025-04-13T16:12:14.7127672Z ##[endgroup]
2025-04-13T16:12:14.7273937Z ##[group]Run pipx install hatch
2025-04-13T16:12:14.7275118Z [36;1mpipx install hatch[0m
2025-04-13T16:12:14.7334207Z shell: /usr/bin/bash -e {0}
2025-04-13T16:12:14.7335200Z env:
2025-04-13T16:12:14.7336241Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:14.7337981Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib/pkgconfig
2025-04-13T16:12:14.7339710Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:14.7341592Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:14.7343174Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:14.7345982Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib:/opt/hostedtoolcache/Python/3.11.11/x64/lib:/opt/hostedtoolcache/Python/3.10.16/x64/lib
2025-04-13T16:12:14.7348524Z ##[endgroup]
2025-04-13T16:12:14.8846499Z creating virtual environment...
2025-04-13T16:12:14.9775484Z installing hatch...
2025-04-13T16:12:21.2964532Z done! ✨ 🌟 ✨
2025-04-13T16:12:21.2965231Z   installed package hatch 1.14.1, installed using Python 3.12.3
2025-04-13T16:12:21.2965840Z   These apps are now globally available
2025-04-13T16:12:21.2966260Z     - hatch
2025-04-13T16:12:21.3169975Z ##[group]Run cd packages/markitdown; hatch test
2025-04-13T16:12:21.3170393Z [36;1mcd packages/markitdown; hatch test[0m
2025-04-13T16:12:21.3218985Z shell: /usr/bin/bash -e {0}
2025-04-13T16:12:21.3219241Z env:
2025-04-13T16:12:21.3219502Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:21.3219942Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib/pkgconfig
2025-04-13T16:12:21.3220354Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:21.3220715Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:21.3221202Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.9/x64
2025-04-13T16:12:21.3221844Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.9/x64/lib:/opt/hostedtoolcache/Python/3.11.11/x64/lib:/opt/hostedtoolcache/Python/3.10.16/x64/lib
2025-04-13T16:12:21.3222447Z ##[endgroup]
2025-04-13T16:12:21.5534018Z Creating environment: hatch-test.py3.12
2025-04-13T16:12:21.6035280Z Installing project in development mode
2025-04-13T16:12:23.5945788Z Checking dependencies
2025-04-13T16:12:23.6400649Z Syncing dependencies
2025-04-13T16:12:28.4517019Z ============================= test session starts ==============================
2025-04-13T16:12:28.4518000Z platform linux -- Python 3.12.3, pytest-8.3.5, pluggy-1.5.0
2025-04-13T16:12:28.4518844Z rootdir: /home/runner/work/markitdown/markitdown/packages/markitdown
2025-04-13T16:12:28.4519544Z configfile: pyproject.toml
2025-04-13T16:12:28.4519901Z plugins: rerunfailures-14.0, anyio-4.9.0, xdist-3.6.1, mock-3.14.0
2025-04-13T16:12:28.4520261Z collected 172 items
2025-04-13T16:12:28.4520604Z 
2025-04-13T16:12:30.2503004Z tests/test_cli_misc.py ..                                                [  1%]
2025-04-13T16:13:07.4002577Z tests/test_cli_vectors.py ......F...........F...........F.....ssssssssss [ 27%]
2025-04-13T16:13:09.4468058Z ss..                                                                     [ 30%]
2025-04-13T16:13:09.7902065Z tests/test_module_misc.py ......ss.ss                                    [ 36%]
2025-04-13T16:13:13.5263257Z tests/test_module_vectors.py ........................F..............F... [ 61%]
2025-04-13T16:13:20.3129233Z ...........F.....sssssssssssssss.........F..............F.........       [100%]
2025-04-13T16:13:20.3129875Z 
2025-04-13T16:13:20.3130102Z =================================== FAILURES ===================================
2025-04-13T16:13:20.3130768Z _____________________ test_output_to_stdout[test_vector6] ______________________
2025-04-13T16:13:20.3131502Z 
2025-04-13T16:13:20.3131867Z shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
2025-04-13T16:13:20.3133741Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3134850Z 
2025-04-13T16:13:20.3135169Z     @pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
2025-04-13T16:13:20.3135990Z     def test_output_to_stdout(shared_tmp_dir, test_vector) -> None:
2025-04-13T16:13:20.3136660Z         """Test that the CLI outputs to stdout correctly."""
2025-04-13T16:13:20.3137159Z     
2025-04-13T16:13:20.3137486Z         result = subprocess.run(
2025-04-13T16:13:20.3137948Z             [
2025-04-13T16:13:20.3138286Z                 "python",
2025-04-13T16:13:20.3138671Z                 "-m",
2025-04-13T16:13:20.3139035Z                 "markitdown",
2025-04-13T16:13:20.3139544Z                 os.path.join(TEST_FILES_DIR, test_vector.filename),
2025-04-13T16:13:20.3140091Z             ],
2025-04-13T16:13:20.3140440Z             capture_output=True,
2025-04-13T16:13:20.3141031Z             text=True,
2025-04-13T16:13:20.3141401Z         )
2025-04-13T16:13:20.3141703Z     
2025-04-13T16:13:20.3142211Z         assert result.returncode == 0, f"CLI exited with error: {result.stderr}"
2025-04-13T16:13:20.3142887Z         for test_string in test_vector.must_include:
2025-04-13T16:13:20.3143725Z >           assert test_string in result.stdout
2025-04-13T16:13:20.3144712Z E           assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
2025-04-13T16:13:20.3147122Z E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n' = CompletedProcess(args=['python', '-m', 'markitdown', '/home/runner/work/markitdown/markitdown/packages/markitdown/test...ut may not work\n  warn("Couldn\'t find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)\n').stdout
2025-04-13T16:13:20.3148828Z 
2025-04-13T16:13:20.3149064Z tests/test_cli_vectors.py:67: AssertionError
2025-04-13T16:13:20.3149725Z ______________________ test_output_to_file[test_vector6] _______________________
2025-04-13T16:13:20.3150230Z 
2025-04-13T16:13:20.3150552Z shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
2025-04-13T16:13:20.3152555Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3153553Z 
2025-04-13T16:13:20.3153823Z     @pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
2025-04-13T16:13:20.3154583Z     def test_output_to_file(shared_tmp_dir, test_vector) -> None:
2025-04-13T16:13:20.3155214Z         """Test that the CLI outputs to a file correctly."""
2025-04-13T16:13:20.3155685Z     
2025-04-13T16:13:20.3156146Z         output_file = os.path.join(shared_tmp_dir, test_vector.filename + ".output")
2025-04-13T16:13:20.3156729Z         result = subprocess.run(
2025-04-13T16:13:20.3157078Z             [
2025-04-13T16:13:20.3157413Z                 "python",
2025-04-13T16:13:20.3157723Z                 "-m",
2025-04-13T16:13:20.3158318Z                 "markitdown",
2025-04-13T16:13:20.3158642Z                 "-o",
2025-04-13T16:13:20.3158933Z                 output_file,
2025-04-13T16:13:20.3159371Z                 os.path.join(TEST_FILES_DIR, test_vector.filename),
2025-04-13T16:13:20.3159811Z             ],
2025-04-13T16:13:20.3160089Z             capture_output=True,
2025-04-13T16:13:20.3160436Z             text=True,
2025-04-13T16:13:20.3160721Z         )
2025-04-13T16:13:20.3161183Z     
2025-04-13T16:13:20.3161603Z         assert result.returncode == 0, f"CLI exited with error: {result.stderr}"
2025-04-13T16:13:20.3162319Z         assert os.path.exists(output_file), f"Output file not created: {output_file}"
2025-04-13T16:13:20.3162838Z     
2025-04-13T16:13:20.3163116Z         with open(output_file, "r") as f:
2025-04-13T16:13:20.3163491Z             output_data = f.read()
2025-04-13T16:13:20.3163889Z             for test_string in test_vector.must_include:
2025-04-13T16:13:20.3164335Z >               assert test_string in output_data
2025-04-13T16:13:20.3165250Z E               AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3165751Z 
2025-04-13T16:13:20.3165919Z tests/test_cli_vectors.py:96: AssertionError
2025-04-13T16:13:20.3166452Z ______________ test_input_from_stdin_without_hints[test_vector6] _______________
2025-04-13T16:13:20.3166854Z 
2025-04-13T16:13:20.3167129Z shared_tmp_dir = PosixPath('/tmp/pytest-of-runner/pytest-0/pytest_tmp0')
2025-04-13T16:13:20.3168487Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3169339Z 
2025-04-13T16:13:20.3169563Z     @pytest.mark.parametrize("test_vector", CLI_TEST_VECTORS)
2025-04-13T16:13:20.3170199Z     def test_input_from_stdin_without_hints(shared_tmp_dir, test_vector) -> None:
2025-04-13T16:13:20.3170997Z         """Test that the CLI readds from stdin correctly."""
2025-04-13T16:13:20.3171407Z     
2025-04-13T16:13:20.3171651Z         test_input = b""
2025-04-13T16:13:20.3172343Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T16:13:20.3173007Z             test_input = stream.read()
2025-04-13T16:13:20.3173393Z     
2025-04-13T16:13:20.3173670Z         result = subprocess.run(
2025-04-13T16:13:20.3174003Z             [
2025-04-13T16:13:20.3174267Z                 "python",
2025-04-13T16:13:20.3174562Z                 "-m",
2025-04-13T16:13:20.3174857Z                 "markitdown",
2025-04-13T16:13:20.3175259Z                 os.path.join(TEST_FILES_DIR, test_vector.filename),
2025-04-13T16:13:20.3175681Z             ],
2025-04-13T16:13:20.3175958Z             input=test_input,
2025-04-13T16:13:20.3176299Z             capture_output=True,
2025-04-13T16:13:20.3176638Z             text=False,
2025-04-13T16:13:20.3176917Z         )
2025-04-13T16:13:20.3177170Z     
2025-04-13T16:13:20.3177543Z         stdout = result.stdout.decode(locale.getpreferredencoding())
2025-04-13T16:13:20.3178056Z         assert (
2025-04-13T16:13:20.3178352Z             result.returncode == 0
2025-04-13T16:13:20.3178825Z         ), f"CLI exited with error: {result.stderr.decode('utf-8')}"
2025-04-13T16:13:20.3179322Z         for test_string in test_vector.must_include:
2025-04-13T16:13:20.3179751Z >           assert test_string in stdout
2025-04-13T16:13:20.3180604Z E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
2025-04-13T16:13:20.3181282Z 
2025-04-13T16:13:20.3181452Z tests/test_cli_vectors.py:129: AssertionError
2025-04-13T16:13:20.3181989Z _______________________ test_convert_local[test_vector9] _______________________
2025-04-13T16:13:20.3182365Z 
2025-04-13T16:13:20.3183341Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3184369Z 
2025-04-13T16:13:20.3184638Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T16:13:20.3185167Z     def test_convert_local(test_vector):
2025-04-13T16:13:20.3185583Z         """Test the conversion of a local file."""
2025-04-13T16:13:20.3185982Z         markitdown = MarkItDown()
2025-04-13T16:13:20.3186310Z     
2025-04-13T16:13:20.3186587Z         result = markitdown.convert(
2025-04-13T16:13:20.3187095Z             os.path.join(TEST_FILES_DIR, test_vector.filename), url=test_vector.url
2025-04-13T16:13:20.3187604Z         )
2025-04-13T16:13:20.3187893Z         for string in test_vector.must_include:
2025-04-13T16:13:20.3188312Z >           assert string in result.markdown
2025-04-13T16:13:20.3189134Z E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3190441Z E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55fa302a80>.markdown
2025-04-13T16:13:20.3191480Z 
2025-04-13T16:13:20.3191670Z tests/test_module_vectors.py:69: AssertionError
2025-04-13T16:13:20.3192229Z _________________ test_convert_stream_with_hints[test_vector9] _________________
2025-04-13T16:13:20.3192629Z 
2025-04-13T16:13:20.3193607Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3194458Z 
2025-04-13T16:13:20.3194713Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T16:13:20.3195262Z     def test_convert_stream_with_hints(test_vector):
2025-04-13T16:13:20.3195803Z         """Test the conversion of a stream with full stream info."""
2025-04-13T16:13:20.3196310Z         markitdown = MarkItDown()
2025-04-13T16:13:20.3196641Z     
2025-04-13T16:13:20.3196907Z         stream_info = StreamInfo(
2025-04-13T16:13:20.3197536Z             extension=os.path.splitext(test_vector.filename)[1],
2025-04-13T16:13:20.3198025Z             mimetype=test_vector.mimetype,
2025-04-13T16:13:20.3198433Z             charset=test_vector.charset,
2025-04-13T16:13:20.3198797Z         )
2025-04-13T16:13:20.3199042Z     
2025-04-13T16:13:20.3199472Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T16:13:20.3200047Z             result = markitdown.convert(
2025-04-13T16:13:20.3200574Z                 stream, stream_info=stream_info, url=test_vector.url
2025-04-13T16:13:20.3201311Z             )
2025-04-13T16:13:20.3201632Z             for string in test_vector.must_include:
2025-04-13T16:13:20.3202064Z >               assert string in result.markdown
2025-04-13T16:13:20.3202937Z E               AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3204250Z E                +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9dc9910>.markdown
2025-04-13T16:13:20.3204929Z 
2025-04-13T16:13:20.3205107Z tests/test_module_vectors.py:90: AssertionError
2025-04-13T16:13:20.3205655Z _______________ test_convert_stream_without_hints[test_vector9] ________________
2025-04-13T16:13:20.3206053Z 
2025-04-13T16:13:20.3206991Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3207821Z 
2025-04-13T16:13:20.3208065Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T16:13:20.3208618Z     def test_convert_stream_without_hints(test_vector):
2025-04-13T16:13:20.3209349Z         """Test the conversion of a stream with no stream info."""
2025-04-13T16:13:20.3209830Z         markitdown = MarkItDown()
2025-04-13T16:13:20.3210193Z     
2025-04-13T16:13:20.3210610Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T16:13:20.3211535Z             result = markitdown.convert(stream, url=test_vector.url)
2025-04-13T16:13:20.3212037Z             for string in test_vector.must_include:
2025-04-13T16:13:20.3212480Z >               assert string in result.markdown
2025-04-13T16:13:20.3213416Z E               AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3214742Z E                +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9da0c50>.markdown
2025-04-13T16:13:20.3215439Z 
2025-04-13T16:13:20.3215612Z tests/test_module_vectors.py:103: AssertionError
2025-04-13T16:13:20.3216170Z _____________________ test_convert_file_uri[test_vector9] ______________________
2025-04-13T16:13:20.3216562Z 
2025-04-13T16:13:20.3217547Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3218418Z 
2025-04-13T16:13:20.3218677Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T16:13:20.3219198Z     def test_convert_file_uri(test_vector):
2025-04-13T16:13:20.3219635Z         """Test the conversion of a file:// URI."""
2025-04-13T16:13:20.3220052Z         markitdown = MarkItDown()
2025-04-13T16:13:20.3220389Z     
2025-04-13T16:13:20.3220656Z         result = markitdown.convert(
2025-04-13T16:13:20.3221386Z             Path(os.path.join(TEST_FILES_DIR, test_vector.filename)).as_uri(),
2025-04-13T16:13:20.3221912Z             url=test_vector.url,
2025-04-13T16:13:20.3222235Z         )
2025-04-13T16:13:20.3222524Z         for string in test_vector.must_include:
2025-04-13T16:13:20.3223124Z >           assert string in result.markdown
2025-04-13T16:13:20.3223977Z E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3225258Z E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f831fad0>.markdown
2025-04-13T16:13:20.3225932Z 
2025-04-13T16:13:20.3226110Z tests/test_module_vectors.py:139: AssertionError
2025-04-13T16:13:20.3226638Z _____________________ test_convert_data_uri[test_vector9] ______________________
2025-04-13T16:13:20.3227021Z 
2025-04-13T16:13:20.3227971Z test_vector = FileTestVector(filename='test_mskanji.csv', mimetype='text/csv', charset='cp932', url=None, must_include=['名前,年齢,住所', '佐藤太郎,30,東京', '三木英子,25,大阪', '髙橋淳,35,名古屋'], must_not_include=[])
2025-04-13T16:13:20.3228846Z 
2025-04-13T16:13:20.3229099Z     @pytest.mark.parametrize("test_vector", GENERAL_TEST_VECTORS)
2025-04-13T16:13:20.3229610Z     def test_convert_data_uri(test_vector):
2025-04-13T16:13:20.3230012Z         """Test the conversion of a data URI."""
2025-04-13T16:13:20.3230402Z         markitdown = MarkItDown()
2025-04-13T16:13:20.3230735Z     
2025-04-13T16:13:20.3231266Z         data = ""
2025-04-13T16:13:20.3231717Z         with open(os.path.join(TEST_FILES_DIR, test_vector.filename), "rb") as stream:
2025-04-13T16:13:20.3232350Z             data = base64.b64encode(stream.read()).decode("utf-8")
2025-04-13T16:13:20.3232802Z         mimetype = test_vector.mimetype
2025-04-13T16:13:20.3233210Z         data_uri = f"data:{mimetype};base64,{data}"
2025-04-13T16:13:20.3233586Z     
2025-04-13T16:13:20.3233849Z         result = markitdown.convert(
2025-04-13T16:13:20.3234205Z             data_uri,
2025-04-13T16:13:20.3234766Z             url=test_vector.url,
2025-04-13T16:13:20.3235099Z         )
2025-04-13T16:13:20.3235388Z         for string in test_vector.must_include:
2025-04-13T16:13:20.3235817Z >           assert string in result.markdown
2025-04-13T16:13:20.3236653Z E           AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3237913Z E            +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f83f79b0>.markdown
2025-04-13T16:13:20.3238568Z 
2025-04-13T16:13:20.3238738Z tests/test_module_vectors.py:160: AssertionError
2025-04-13T16:13:20.3239201Z =============================== warnings summary ===============================
2025-04-13T16:13:20.3240073Z ../../../../../.local/share/hatch/env/virtual/markitdown/H_uUSwZ6/hatch-test.py3.12/lib/python3.12/site-packages/pydub/utils.py:170
2025-04-13T16:13:20.3242220Z   /home/runner/.local/share/hatch/env/virtual/markitdown/H_uUSwZ6/hatch-test.py3.12/lib/python3.12/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
2025-04-13T16:13:20.3243790Z     warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2025-04-13T16:13:20.3244307Z 
2025-04-13T16:13:20.3244603Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-04-13T16:13:20.3245197Z =========================== short test summary info ============================
2025-04-13T16:13:20.3246499Z FAILED tests/test_cli_vectors.py::test_output_to_stdout[test_vector6] - assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
2025-04-13T16:13:20.3248877Z  +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n' = CompletedProcess(args=['python', '-m', 'markitdown', '/home/runner/work/markitdown/markitdown/packages/markitdown/test...ut may not work\n  warn("Couldn\'t find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)\n').stdout
2025-04-13T16:13:20.3251599Z FAILED tests/test_cli_vectors.py::test_output_to_file[test_vector6] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3253567Z FAILED tests/test_cli_vectors.py::test_input_from_stdin_without_hints[test_vector6] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |\n'
2025-04-13T16:13:20.3255515Z FAILED tests/test_module_vectors.py::test_convert_local[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3257183Z  +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55fa302a80>.markdown
2025-04-13T16:13:20.3259199Z FAILED tests/test_module_vectors.py::test_convert_stream_with_hints[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3260767Z  +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9dc9910>.markdown
2025-04-13T16:13:20.3262598Z FAILED tests/test_module_vectors.py::test_convert_stream_without_hints[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3264175Z  +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f9da0c50>.markdown
2025-04-13T16:13:20.3265749Z FAILED tests/test_module_vectors.py::test_convert_file_uri[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3267249Z  +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f831fad0>.markdown
2025-04-13T16:13:20.3268769Z FAILED tests/test_module_vectors.py::test_convert_data_uri[test_vector9] - AssertionError: assert '名前,年齢,住所' in '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |'
2025-04-13T16:13:20.3270262Z  +  where '| 名前 | 年齢 | 住所 |\n| --- | --- | --- |\n| 佐藤太郎 | 30 | 東京 |\n| 三木英子 | 25 | 大阪 |\n| 髙橋淳 | 35 | 名古屋 |' = <markitdown._base_converter.DocumentConverterResult object at 0x7f55f83f79b0>.markdown
2025-04-13T16:13:20.3271330Z ============ 8 failed, 133 passed, 31 skipped, 1 warning in 55.66s =============
2025-04-13T16:13:20.7202655Z ##[error]Process completed with exit code 1.
2025-04-13T16:13:20.7322600Z Post job cleanup.
2025-04-13T16:13:20.8273598Z [command]/usr/bin/git version
2025-04-13T16:13:20.8310118Z git version 2.49.0
2025-04-13T16:13:20.8361700Z Temporarily overriding HOME='/home/runner/work/_temp/27701047-55e4-4eb6-a51f-fe28f5021f6e' before making global git config changes
2025-04-13T16:13:20.8363005Z Adding repository directory to the temporary git global config as a safe directory
2025-04-13T16:13:20.8367626Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/markitdown/markitdown
2025-04-13T16:13:20.8404272Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2025-04-13T16:13:20.8437758Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2025-04-13T16:13:20.8677292Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2025-04-13T16:13:20.8702685Z http.https://github.com/.extraheader
2025-04-13T16:13:20.8715645Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2025-04-13T16:13:20.8746500Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2025-04-13T16:13:20.9087370Z Cleaning up orphan processes
