actions/setup-python@v5

3.13
cache: pip
cache-dependency-path: docs/requirements.txt


update-environment:
allow-prereleases:
freethreaded:
##[endgroup]

3 13 2
##[endgroup]
[command]/opt/hostedtoolcache/Python/3.13.2/x64/bin/pip cache dir
/home/runner/.cache/pip
Cache hit for: setup-python-Linux-x64-24.04-Ubuntu-python-3.13.2-pip-36e4e3d0ff2183e0234455b531be7c29e94c3ba5d3f6a32f3d9ff5bbf06af8f7
Received 4194304 of 60356612 (6.9%), 4.0 MBs/sec
Received 60356612 of 60356612 (100.0%), 37.4 MBs/sec
Cache Size: ~58 MB (60356612 B)
[command]/usr/bin/tar -xf /home/runner/work/_temp/ae4f28ac-5da0-4834-82d1-8fbe32d32586/cache.tzst -P -C /home/runner/work/django/django --use-compress-program unzstd
Cache restored successfully
Cache restored from key: setup-python-Linux-x64-24.04-Ubuntu-python-3.13.2-pip-36e4e3d0ff2183e0234455b531be7c29e94c3ba5d3f6a32f3d9ff5bbf06af8f7
